development:
  adapter: postgresql
  encoding: unicode
  database: tempo
  pool: 
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tempo
  pool: 
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tempo
  pool: 
  username: 
  password:
