# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 826800f00d450e6b035d18bb5689e15c5c9bba42530c5136828ad8a206cbfc8e7931bbadce0f0bc15d70dff477787ff851a7b1f271bfeb7883180c4fc7edbe13

test:
  secret_key_base: 0254d2b71abb1d80f4dd0dbb6cb7040c45dc4f65e15e6ca80b080000a5982b1c3d057e8ac4933947a4978dec80504946f9f9a290ac68ab79ca97b2843a63f1e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
